# Generated by Django 4.1.7 on 2023-05-20 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='hire_date',
            new_name='hiredate',
        ),
    ]
